name: Deploy to Vercel
on:
  workflow_call:
jobs:
  deploy-vercel:
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }};
          else
            vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }};
          fi

      - name: Build Project Artifacts
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }};
          else
            vercel build --token=${{ secrets.VERCEL_TOKEN }};
          fi

      - name: Deploy Project Artifacts to Vercel
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }};
          else
            vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }};
          fi
