name: CI/CD Pipeline (dev)
on:
  push:
    branches:
      - refactor
  pull_request: 
    branches:
      - refactor
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  deploy-vercel:
    needs: [test]
    uses: ./.github/workflows/deploy-vercel.yaml
    secrets: inherit
  e2e:
    needs: [deploy-vercel]
    uses: ./.github/workflows/e2e.yaml
    with:
      env: dev 