name: End to End Test
on:
  workflow_call:
    inputs:
      node-version:
        type: number
        required: false
        default: 20
      env:
        type: string # dev | prod
        required: true
jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
        APP_ENV: ${{ inputs.env }}
        NOTION_ROOT_PAGE_ID: ${{ secrets.NOTION_ROOT_PAGE_ID }}
        NOTION_ACTIVE_USER_ID: ${{ secrets.NOTION_ACTIVE_USER_ID }}
        NOTION_AUTH_TOKEN: ${{ secrets.NOTION_AUTH_TOKEN }}
        NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
        NOTION_DB_ID: ${{ secrets.NOTION_DB_ID }}
        NOTION_PORTFOLIO_PAGE_ID: ${{ secrets.NOTION_PORTFOLIO_PAGE_ID }}
        BLOG_ODR_TOKEN: ${{ secrets.BLOG_ODR_TOKEN }}
        NEXT_PUBLIC_GA_ID: ${{ secrets.NEXT_PUBLIC_GA_ID }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'yarn'

    - name: Cache dependencies
      id: dependencies-cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        path: '**/node_modules'
        restore-keys: |
          ${{ runner.os }}-node-
            
    - name: Install Packages
      if: steps.dependencies-cache.outputs.cache-hit != 'true'
      run: yarn install
    
    - name: Build project
      run: yarn build
        
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start e2e test
      run: |
        echo "APP_ENV is ${{ env.APP_ENV }}"
        yarn e2e

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30