# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Send Request to Supabase API
        run: |
          curl -i --fail -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/keep-alive?select=*&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
      - name: Keepalive Workflow
        if: github.event_name == 'schedule'
        uses: liskin/gh-workflow-keepalive@v1
